language: node_js
before_install:
  - npm i -g chrome-webstore-upload-cli web-ext

cache:
  yarn: true
  directories: 
  - node_modules
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master