language: node_js
before_install:
  - npm i -g chrome-webstore-upload-cli
cache:
  directories: 
  - node_modules
deploy:
  provider: script
  script: npm run upload:chrome
  on:
    all_branches: true